### ISSUE TITLE
Some problem with validate method on different OS

### ISSUE THREAD

**Issue by jgorski21** [Pawlik7/regon-demo#17]
function validate(data) {
    if (bir_error_js_1.default.looksLike(data)) {
        throw bir_error_js_1.default.fromResponse(data);
    }
    return data;
}

On my macOS local machine and containerized api everything works well.

In production im using debian containerized api.

When using local machine I has that result:
(Good response)
{
  regon: 'xxxx',
  nip: '1010009606',
  statusNip: undefined,
  nazwa: 'MxxX xxx S.P.A. (xxxxxx xxx) xxxx x xx',
  wojewodztwo: 'xx',
  powiat: 'xxxx',
  gmina: 'xxxxxxx',
  miejscowosc: 'xxxxxx',
  kodPocztowy: 'xx-xxx',
  ulica: 'xxx',
  nrNieruchomosci: 'x',
  nrLokalu: undefined,
  typ: 'P',
  silosID: 'x',
  dataZakonczeniaDzialalnosci: undefined,
  miejscowoscPoczty: 'xxx'
}
1010009606

but on debian I get that error:
 BirError: No data found for the specified search criteria.
 at new BirError (/usr/src/app/node_modules/bir1/dist/bir-error.js:9:15)
 at BirError.fromResponse (/usr/src/app/node_modules/bir1/dist/bir-error.js:15:23)
 at validate (/usr/src/app/node_modules/bir1/dist/bir.js:25:38)
 at Bir.search (/usr/src/app/node_modules/bir1/dist/bir.js:64:16)
 at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
 response: {
 errorCode: '4',
 errorMessagePl: 'Nie znaleziono podmiotu dla podanych kryteriów wyszukiwania.',
 errorMessageEn: 'No data found for the specified search criteria.',
 nip: '1010009606'
 }
 
 in that two cases im using as search parameter nip.

**Comment by pawel-id** [comment]
This library is cross platform. I would say posix is somehow preferred because the unit tests runs on ubuntu :).

The company with NIP number you are searching is available on production database (with key provided) and not available in non production (without key). Then I guess that in your containerized environment has a missing key.

**Comment by jgorski21** [comment]
It was that about key, thanks :D. Really simple thing.
